mahjong/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mahjong_records/', include('mahjong_records.urls')),
]

mahjong_records/urls.py
from django.urls import path

from . import views

app_name="mahjong_records"

urlpatterns = [
    path('', views.index, name='index'),
    path('total/', views.total, name="total"),
    path('career/', views.career, name="career"),
    path('record_match/', views.record_match, name="record_match"),
    path('resister_match/', views.resister_match, name="resister_match"),
    path('record_user/', views.record_user, name="record_user"),
    path('resister_user/', views.resister_user, name="resister_user"),
    path('<int:user_id>/user_detail/', views.user_detail, name="user_detail"),
    path('<int:game_id>/game_detail/', views.game_detail, name="game_detail"),
]

mahjong_records/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone

# Create your models here.

class User(models.Model):
  name = models.CharField(verbose_name='名前', max_length=32)
  created_at = models.DateTimeField(verbose_name='作成日時')

  def __str__(self):
    return self.name

class Game(models.Model):
  playing_date = models.DateTimeField(verbose_name='ゲーム開催日時')
  def __str__(self):
    return timezone.localtime(self.playing_date).strftime("%Y/%m/%d %H:%M")

  def users(self):
    users = self.record_set.all().order_by("rank")
    return users

class Record(models.Model):
  user = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name='user_id')
  game = models.ForeignKey(Game, on_delete=models.CASCADE, verbose_name='game_id')
  rank = models.IntegerField(default=1)
  score = models.IntegerField(default=25000)
  point = models.FloatField(default=0)

  def __str__(self):
    return str(self.rank)+"着,"+self.user.name+str(self.point)+timezone.localtime(self.game.playing_date).strftime("%Y/%m/%d %H:%M")

mahjong_records/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render

# Create your views here.
from django.http import HttpResponse
from django.template import loader
from django.db import models
from .models import User, Record, Game
import datetime, operator, logging
import numpy as np

def index(request):
  today = datetime.date.today()
  game = Game.objects.filter(playing_date__date=today).order_by("-playing_date")
  template = loader.get_template('mahjong_records/index.html')
  context = {
    'game':game,
  }
  return render(request, 'mahjong_records/index.html', context)

def total(request):
  today = datetime.date.today()
  game = Game.objects.filter(playing_date__date=today)
  users = User.objects.filter(record__game__playing_date__date=today).distinct()
  user_data = [{'name':user.name, 'id':user.id} for user in users]
  for i, user in enumerate(users):
    user_data[i].update(user.record_set.filter(game__playing_date__date=today).aggregate(sum_point=models.Sum('point'),ave_rank=models.Avg('rank'),max_score=models.Max('score'),ave_score=models.Avg('score'), count_match=models.Count('rank')))
    today_records = user.record_set.filter(game__playing_date__date=today)
    counts = today_records.count()
    top = today_records.filter(rank=1).count()
    worst = today_records.filter(rank=4).count()
    user_data[i].update({"top_rate":float(top/counts), "avoid_worst_rate":1-float(worst/counts)})
  template = loader.get_template('mahjong_records/total.html')
  context = {
    'game':game,
    'stats':sorted(user_data, key=operator.itemgetter('sum_point'), reverse=True),
  }
  return render(request, 'mahjong_records/total.html', context)

def career(request):
  users = User.objects.all()
  user_data = [{'name':user.name, 'id':user.id} for user in users]
  for i, user in enumerate(users):
    if user.record_set.count() > 0:
      user_data[i].update(user.record_set.aggregate(sum_point=models.Sum('point'),ave_rank=models.Avg('rank'),max_score=models.Max('score'),ave_score=models.Avg('score'), count_match=models.Count('rank')))
      counts = user.record_set.count()
      top = user.record_set.filter(rank=1).count()
      worst = user.record_set.filter(rank=4).count()
      user_data[i].update({"top_rate":float(top/counts), "avoid_worst_rate":1-float(worst/counts)})
    else:
      user_data[i].update({"sum_point":0,"ave_rank":0,"max_score":0,"ave_score":0, "count_match":0, "top_rate":0, "avoid_worst_rate":0})
  template = loader.get_template('mahjong_records/career.html')
  context = {
    'stats':sorted(user_data, key=operator.itemgetter('sum_point'), reverse=True),
  }
  return HttpResponse(template.render(context, request))

def record_match(request):
  users = User.objects.all()
  home = {"east":"東家", "south":"南家", "west":"西家", "north":"北家"}

  return render(request, 'mahjong_records/record_match.html', {'users':users, 'home':home,})

def resister_match(request):
  users = User.objects.all()
  home = {"east":"東家", "south":"南家", "west":"西家", "north":"北家"}
  user_score = {}
  uma_oka = [50.0, 10.0, -10.0, -30.0]
  temp = []

  for player in home:
    user_score[request.POST[player]] = int(request.POST[player+'_score'])

  if (sum(user_score.values())!=(250*4)) or (0 in user_score) or (len(user_score) != len(set(user_score))):
    return render(request, 'mahjong_records/record_match.html', {
      'users':users, 
      'home':home,
      'error_message':"正しく入力してください",
      'request':request
      })
  else:
    today = datetime.datetime.today()
    game = Game.objects.create(playing_date=today)
    arr = np.array(list(user_score.values()))
    u,inv,k=np.unique(-np.sort(arr)[::-1], return_inverse=True, return_counts=True)
    for i, userid_score in enumerate(sorted(user_score.items(), key=lambda x:x[1], reverse=True)):
      user_score = userid_score[1]*100
      rank=k[:inv[i]].sum()+1
      user_point = float(user_score/1000)+uma_oka[rank-1]/k[inv[i]]-30.0
      Record.objects.create(rank=rank, score=user_score, point=user_point, user=users.get(id=userid_score[0]), game=game)

    return render(request, 'mahjong_records/resister_success.html', {'message':"対局結果を記録しました."})

def record_user(request):
   return render(request, 'mahjong_records/record_user.html')

def resister_user(request):
  today = datetime.datetime.today()
  user = User.objects.create(name=request.POST["name"], created_at=today)
  return render(request, 'mahjong_records/resister_success.html', {'message':"プレイヤー登録を完了しました."})

def user_detail(request, user_id):
  user = User.objects.get(id=user_id)
  if user.record_set.count() > 0:
    records = user.record_set.all().order_by("-game__playing_date")
    stats = user.record_set.aggregate(sum_point=models.Sum('point'),ave_rank=models.Avg('rank'),max_score=models.Max('score'),ave_score=models.Avg('score'), count_match=models.Count('rank'))
    counts = user.record_set.count()
    top = user.record_set.filter(rank=1).count()
    worst = user.record_set.filter(rank=4).count()
    stats.update({"top_rate":float(top/counts), "avoid_worst_rate":1-float(worst/counts)})
  return render(request, 'mahjong_records/user_detail.html', {'user':user, 'stats':stats, 'records':records})

def game_detail(request, game_id):
  game = Game.objects.get(id=game_id)
  records = game.record_set.all().order_by("rank")
  return render(request, 'mahjong_records/game_detail.html', {'records':records})

mahjong_records/templates/mahjong_records/base.html
<!DOCTYPE html>
<html lang="ja">
<head>
{% load static %}
<!DOCTYPE html>
<html lang="ja">
<meta charset="UTF-8">
<title>麻雀成績記録アプリ</title>
<link rel="stylesheet" type="text/css" href="{% static 'mahjong_records/style.css' %}">
<nav>
  <ul>
    <li><a href="{% url 'mahjong_records:index'%}" class="default_text">本日の対局結果</a></li>
    <li><a href="{% url 'mahjong_records:total'%}" class="default_text">本日の総合成績</a></li>
    <li><a href="{% url 'mahjong_records:career'%}" class="default_text">通算成績</a></li>
    <li><a href="{% url 'mahjong_records:record_match' %}" class="register_text">対局結果の記録</a></li>
    <li><a href="{% url 'mahjong_records:record_user' %}" class="register_text">プレイヤー登録</a></li>
  </ul>
</nav>
</head>
<body>
    {% block content %}
    {% endblock %}
</body>
</html>

mahjong_records/templates/mahjong_records/career.html
{% extends "mahjong_records/base.html" %}
{% block content %}
<h1 align="center"> 通算成績 </h1>
<hr>
<table align="center" border="1">
    <thead>
        <tr>
            <th>順位</th>
            <th>名前</th>
            <th>平均着順</th>
            <th>総合ポイント</th>
            <th>最大スコア</th>
            <th>平均スコア</th>
            <th>トップ率</th>
            <th>4着回避率</th>
            <th>総対局数</th>
        </tr>
    </thead>
    <tbody>
        {% for user in stats %}
            <tr>  
                <th>{{forloop.counter}}</th>
                <th><strong><a  href="{% url 'mahjong_records:user_detail' user.id %}">{{user.name}}</a></strong></th>
                <th>{{user.ave_rank|floatformat:2}}</th>
                <th><strong>{{user.sum_point|floatformat:1}}</strong></th>
                <th>{{user.max_score}}</th>
                <th>{{user.ave_score|floatformat:2}}</th>
                <th>{{user.top_rate|floatformat:2}}</th>
                <th>{{user.avoid_worst_rate|floatformat:2}}</th>
                <th>{{user.count_match}}</th>
            </tr>
        {%endfor%}
    </tbody>
</table>
<hr>
{% endblock %}

mahjong_records/templates/mahjong_records/game_detail.html
{% extends "mahjong_records/base.html" %}
{% block content %}
<h1 align="center"> {{records.first.game.playing_date|date:"20y/n/j H:i"}}の対局結果 </h1>
<hr>
<table align="center" border="1">
    <thead>
        <tr>
            <th>着順</th>
            <th>名前</th>
            <th>点棒</th>
            <th>ポイント</th>
        </tr>
    </thead>
    <tbody>
        {% for record in records %}
            <tr>
                <th><strong>{{record.rank}}</strong></th>
                <th><strong><a  href="{% url 'mahjong_records:user_detail' record.user.id %}">{{record.user.name}}</a></strong></th>
                <th>{{record.score}}</th>
                <th>{{record.point|floatformat:1}}</th>
            </tr>
        {%endfor%}
    </tbody>
</table>
{% endblock%}

mahjong_records/templates/mahjong_records/index.html
{% extends "mahjong_records/base.html" %}
{% block content %}
<h1 align="center"> 本日の対局 </h1>
<hr>
{% if game.exists %}
    {% for halfround in game %}
        <h3 align="center"> {{halfround.playing_date|date:"20y/n/j H:i"}}</h3>
        <table align="center" border="1">
            <thead>
                <tr>
                    <th>着順</th>
                    <th>名前</th>
                    <th>点棒</th>
                    <th>ポイント</th>
                </tr>
            </thead>
            <tbody>
                {% for datas in halfround.users %}
                    <tr>
                        <th><strong>{{datas.rank}}</strong></th>
                        <th><strong><a  href="{% url 'mahjong_records:user_detail' datas.user.id %}">{{datas.user.name}}</a></strong></th>
                        <th>{{datas.score}}</th>
                        <th>{{datas.point|floatformat:1}}</th>
                    </tr>
                {%endfor%}
            </tbody>
        </table>
    <hr>
    {% endfor %}
{% else %}
    <h2>対局なし</h2>
{% endif %}
{% endblock%}

mahjong_records/templates/mahjong_records/record_match.html
{% extends "mahjong_records/base.html" %}
{% block content %}
<h1 align="center"> 対局結果 記録 </h1>
<form action="{% url 'mahjong_records:resister_match' %}" method="post" align="center">
{% csrf_token %}
<fieldset>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for player, ja_player in home.items %}
        <h3>{{ja_player}}</h3>
        <label>プレイヤー</label>
        <select name="{{player}}">
            <option selected="selected" value=0>プレイヤー選択</option>
            {% for user in users %}
                <option value="{{user.id}}">{{user.name}}</option>
            {% endfor %}
        </select>
        <div>
            <label>最終点棒</label>
            <input type="number" name="{{player}}_score" value="250">00
        </div>
    {% endfor %}
</fieldset>
<input type="submit" value="記録">
</form>
{% endblock%}

mahjong_records/templates/mahjong_records/record_user.html
{% extends "mahjong_records/base.html" %}
{% block content %}
<h1 align="center"> プレイヤー登録 </h1>
<form action="{% url 'mahjong_records:resister_user' %}" method="post" align="center">
{% csrf_token %}
<fieldset>
    <div>
        <label>プレイヤー名</label>
        <input type="text" name="name">
    </div>
</fieldset>
<input type="submit" value="記録">
</form>
{% endblock%}

mahjong_records/templates/mahjong_records/resister_match.html
{% extends "mahjong_records/base.html" %}
{% block content %}
<h1 align="center"> 対局結果 記録 </h1>
<h2 align="center" color="green">対局結果を記録しました.</h2>
{% endblock%}

mahjong_records/templates/mahjong_records/resister_success.html
{% extends "mahjong_records/base.html" %}
{% block content %}
<h1 align="center"> 対局結果 記録 </h1>
<h2 align="center" color="green">{{message}}</h2>
{% endblock%}

mahjong_records/templates/mahjong_records/total.html
{% extends "mahjong_records/base.html" %}
{% block content %}
<h1 align="center"> 本日の総合成績 </h1>
<hr>
{% if game.exists %}    
<table align="center" border="1">
    <thead>
        <tr>
            <th>順位</th>
            <th>名前</th>
            <th>平均着順</th>
            <th>総合ポイント</th>
            <th>最大スコア</th>
            <th>平均スコア</th>
            <th>トップ率</th>
            <th>4着回避率</th>
            <th>総対局数</th>
        </tr>
    </thead>
    <tbody>
        {% for user in stats %}
            <tr>  
                <th>{{forloop.counter}}</th>
                <th><strong><a  href="{% url 'mahjong_records:user_detail' user.id %}">{{user.name}}</a></strong></th>
                <th>{{user.ave_rank|floatformat:2}}</th>
                <th><strong>{{user.sum_point|floatformat:1}}</strong></th>
                <th>{{user.max_score}}</th>
                <th>{{user.ave_score|floatformat:2}}</th>
                <th>{{user.top_rate|floatformat:2}}</th>
                <th>{{user.avoid_worst_rate|floatformat:2}}</th>
                <th>{{user.count_match}}</th>
            </tr>
        {%endfor%}
    </tbody>
</table>
<hr>
{% else %}
    <h2>対局なし</h2>
{% endif %}
{% endblock%}

mahjong_records/templates/mahjong_records/user_detail.html
{% extends "mahjong_records/base.html" %}
{% block content %}
<h1 align="center"> {{user.name}} 通算成績</h1>
<hr>
{% if stats %}
  <table align="center" >
    <thead>
        <tr>
            <th>平均着順</th>
            <th>総合ポイント</th>
            <th>最大スコア</th>
            <th>平均スコア</th>
            <th>トップ率</th>
            <th>4着回避率</th>
            <th>総対局数</th>
        </tr>
    </thead>
    <tbody>
        <tr>  
            <th>{{stats.ave_rank|floatformat:2}}</th>
            <th>{{stats.sum_point|floatformat:1}}</th>
            <th>{{stats.max_score}}</th>
            <th>{{stats.ave_score|floatformat:2}}</th>
            <th>{{stats.top_rate|floatformat:2}}</th>
            <th>{{stats.avoid_worst_rate|floatformat:2}}</th>
            <th>{{stats.count_match}}</th>
        </tr>
    </tbody>
  </table>
  <br>
   <table align="center" border="1">
        <thead>
            <tr>
                <th>対局日時</th>
                <th>着順</th>
                <th>点棒</th>
                <th>ポイント</th>
            </tr>
        </thead>
        <tbody>
            {% for data in records %}
                <tr>
                    <th><a  href="{% url 'mahjong_records:game_detail' data.game.id %}">{{data.game.playing_date|date:"20y/n/j H:i"}}</a></th>
                    <th>{{data.rank}}</th>
                    <th>{{data.score}}</th>
                    <th>{{data.point|floatformat:1}}</th>
                </tr>
            {%endfor%}
        </tbody>
    </table>
{% else %}
<h2>対局記録なし</h2>
{% endif %}
{% endblock %}